const NEW_MESSAGE = "NEW_MESSAGE"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"
const NEW_ATTACHMENT = "NEW_ATTACHMENT"
const NEW_REQUEST = "NEW_REQUEST"
const TYPING_STARTED = "TYPING_STARTED"
const TYPING_ENDED = "TYPING_ENDED"


export { NEW_MESSAGE, NEW_MESSAGE_ALERT, NEW_ATTACHMENT, NEW_REQUEST, TYPING_ENDED, TYPING_STARTED }